version: '3.8'

services:
  reverse_proxy:
    container_name: "nginx"
    restart: always
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./reverse_proxy/default.conf:/etc/nginx/sites-available/default
    networks:
      - fullstack
    links:
      - postgres
      - goapi
  postgres:
    container_name: "postgres_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    networks: 
      - fullstack
    volumes:
      - ./psql_data:/var/lib/postgresql/data
  goapi:     
    container_name: "go_api"
    restart: always
    environment:
      -  TEST=false
      -  SQL_DIALECT=postgre
      -  SQL_DRIVER=sql
      -  SQL_USER=postgres
      -  SQL_PASSWORD=postgres
      -  SQL_HOST=postgres
      -  SQL_PORT=5432
      -  SECRET_KEY=56277de1-2c42-4c95-8f3b-a90b05c1b684
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
      - "433:433"
    networks:
      - fullstack
    # we are depending on the mysql backend
    depends_on:
      - postgres
    links: 
      - postgres

networks:
  fullstack:
    driver: bridge